import {node} from './landing.js';
const paths={search:'M21 21l-5-5 M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',document:'M6 3h8l4 4v14H6z M14 3v5h4 M9 12h6 M9 16h6',grid:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',list:'M4 6h16 M4 12h16 M4 18h16',sidebar:'M3 4h18v16H3z M9 4v16',star:'m12 3 3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1z',folder:'M3 6h7l2 2h9v12H3z',close:'M5 5l14 14 M5 19 19 5'};
export function icon(name){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('class','app-icon');svg.setAttribute('fill','none');svg.setAttribute('stroke','currentColor');svg.setAttribute('stroke-width','1.5');svg.setAttribute('stroke-linecap','round');svg.setAttribute('stroke-linejoin','round');svg.setAttribute('aria-hidden','true');const p=document.createElementNS(svg.namespaceURI,'path');p.setAttribute('d',paths[name]||paths.document);svg.append(p);return svg;}
export function iconButton(label,name,onClick){const b=node('button','app-icon-button');b.type='button';b.setAttribute('aria-label',label);b.title=label;b.append(icon(name));b.addEventListener('click',onClick);return b;}
export function searchField(onSearch){const label=node('label','app-search');label.append(icon('search'));const input=node('input');input.type='search';input.placeholder='Search documents';input.setAttribute('aria-label','Search documents');input.addEventListener('input',()=>onSearch(input.value));label.append(input);return label;}
export function sidebar(items,onSelect){const side=node('aside','app-sidebar');side.id='app-sidebar';side.append(node('div','app-space','Northstar workspace'));const nav=node('nav','app-nav');nav.setAttribute('aria-label','Document collections');for(const item of items){const b=node('button','app-nav-row');b.type='button';b.append(icon(item.icon),node('span','',item.label));b.dataset.id=item.id;if(item.id==='all')b.setAttribute('aria-current','page');b.addEventListener('click',()=>{for(const row of nav.children)row.removeAttribute('aria-current');b.setAttribute('aria-current','page');onSelect(item)});nav.append(b);}side.append(nav,node('div','app-section-title','Starred'),node('div','app-hint','Use the star action in a document preview to keep it close.'),node('div','app-section-title','Component library'),node('div','app-hint','Synthetic documents. Layout preview only.'));return side;}
export function viewSwitcher(onChange){const group=node('div','app-view');group.setAttribute('role','group');group.setAttribute('aria-label','Document view');for(const mode of ['grid','list']){const b=iconButton(mode==='grid'?'Grid view':'List view',mode,()=>{for(const child of group.children)child.setAttribute('aria-pressed',String(child===b));onChange(mode)});b.setAttribute('aria-pressed',String(mode==='grid'));group.append(b);}return group;}
export function documentCard(doc,onOpen){const b=node('button','app-card');b.type='button';b.title=doc.title;b.dataset.docId=doc.id;b.setAttribute('aria-label','Open '+doc.title);b.append(node('span','app-card__title',doc.title),node('span','app-card__meta',doc.status+' · '+doc.date));const preview=node('span','app-card__preview');preview.append(node('strong','',doc.heading),node('span','',doc.text),node('strong','','Synthetic example'));b.append(preview);b.addEventListener('click',()=>onOpen(doc,b));return b;}
export function emptyState(title='No documents found'){const el=node('div','app-empty');el.append(node('h2','',title),node('p','','Try another search or choose All documents.'));return el;}
