import type {ReactNode} from 'react';

// React ports of the existing library components, using the Paper product exports.
// Lineage and intentional functional differences: design/IMPLEMENTATION_MAP.md.
export function Icon({name='document'}:{name?:'document'|'folder'|'search'}) {
 const paths={document:'M6 3h8l4 4v14H6z M14 3v5h4 M9 12h6 M9 16h6',folder:'M3 6h7l2 2h9v12H3z',search:'M21 21l-5-5 M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0'};
 return <svg className="library-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]}/></svg>;
}
export function SidebarRow({children,href,active,onClick,tone='brand',disabled=false}:{children:ReactNode;href?:string;active?:boolean;onClick?:()=>void;tone?:string;disabled?:boolean}) {
 const props={className:`library-row tone-${tone}${active?' active':''}`};
 const content=<><Icon name={tone==='brand'?'document':'folder'}/><span>{children}</span></>;
 return href?<a {...props} href={href} aria-current={active?'page':undefined}>{content}</a>:<button {...props} type="button" disabled={disabled} aria-pressed={active} onClick={onClick}>{content}</button>;
}
export function FloatingNavigation(){return <nav className="library-floating-nav" aria-label="Landing"><a className="library-brand" href="#/">ClauseForge</a><a href="#/matters">Product</a><a href="#how-it-works" onClick={e=>{e.preventDefault();document.getElementById('how-it-works')?.scrollIntoView()}}>How it works</a><a href="#about" onClick={e=>{e.preventDefault();document.getElementById('about')?.scrollIntoView()}}>About</a><a className="library-pill small-pill" href="#/matters">Open demo</a></nav>}
export function DemoEntry(){return <div className="library-entry"><FloatingNavigation/><main className="library-hero"><h1>Your space for contracts, clauses, and clear decisions</h1><a className="library-pill" href="#/review">Open sample matter</a></main><section className="library-introduction" id="how-it-works"><p>Review a renewal. Trace its amendments. Test the playbook behind your decisions.</p><p>Synthetic sample matter · No account needed</p><p id="about">Designed and built by Ricardo Zuloaga</p><p className="demo-disclosure">Available now: simulated review, revisions and comments. Explore amendment scope and playbook testing. Word export and AI remain simulated.</p></section></div>}
export function LibraryShell({query,onSearch,children,route="/matters"}:{query:string;onSearch:(s:string)=>void;children:ReactNode;route?:string}){return <div className={"library-shell "+(route.startsWith("/playbooks")?"area-playbook":route.startsWith("/tests")?"area-tests":"area-brand")}><header className="library-topbar"><a href="#/">ClauseForge / Library</a>{["/matters","/documents","/playbooks","/activity"].includes(route)?<label className="library-search"><Icon name="search"/><input type="search" aria-label="Search library" placeholder="Search library" value={query} onChange={e=>onSearch(e.target.value)}/></label>:<span className="library-header-context">ClauseForge workspace</span>}<span>RICARDO ZULOAGA</span></header><div className="library-body"><aside className="library-sidebar"><h2>Ricardo’s workspace</h2><nav aria-label="Workspace"><SidebarRow href="#/matters" active={route.startsWith("/matters")}>All matters</SidebarRow><SidebarRow href="#/documents" active={route==="/documents"}>Documents</SidebarRow><SidebarRow href="#/playbooks" active={route.startsWith("/playbooks")} tone="playbook">Playbooks</SidebarRow><SidebarRow href="#/tests" active={route.startsWith("/tests")} tone="tests">Test runs</SidebarRow></nav><section><h3>Workspace</h3><p>Personal workspace<br/>Synthetic sample documents</p><a href="./index.html">Component library ↗</a></section></aside><main className="library-content">{children}</main></div></div>}
export function DocumentCard({title,meta,heading,children,footer,href}:{title:string;meta:string;heading:string;children:ReactNode;footer:string;href:string}){return <a className="library-document-card" href={href}><h2>{title}</h2><p className="library-card-meta">{meta}</p><div className="library-card-preview"><strong>{heading}</strong><p>{children}</p><strong>{footer}</strong></div></a>}
export function CommentComposer({context,value,onChange,onSubmit}:{context:string;value:string;onChange:(s:string)=>void;onSubmit:()=>void}){return <form className="library-composer" onSubmit={e=>{e.preventDefault();onSubmit()}}><div className="library-context"><Icon/><span><b>{context}</b><small>Comment context</small></span></div><label><span className="visually-hidden">Add clause comment</span><textarea aria-label="Clause comment" rows={2} value={value} onChange={e=>onChange(e.target.value)} placeholder="Add a clause comment…"/></label><button disabled={!value.trim()}>Add comment</button><p>Comments bind to this clause and version.</p></form>}
